import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { Button } from "@/components/ui/button";
import { logout } from "./logout/actions";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex border-b p-2 items-center">
          <nav className="flex-grow">
            <ul className="flex gap-x-4">
              <li className="p-2">
                <Link href="/">Home</Link>
              </li>
              <li className="p-2">
                <Link href="/task">Task</Link>
              </li>
              <li className="p-2">
                <Link href="/shop">Shop</Link>
              </li>
              {!data?.user && (
                <div className="flex-grow flex gap-x-4 justify-end">
                  <li className="p-2">
                    <Link href="login">Login</Link>
                  </li>
                </div>
              )}
            </ul>
          </nav>
          {data?.user && (
            <form>
              <Button variant="outline" formAction={logout}>
                Logout
              </Button>
            </form>
          )}
        </header>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
